# Generated by Django 4.2.2 on 2023-07-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('can_drop', models.CharField(max_length=200)),
                ('chanse', models.IntegerField()),
            ],
        ),
    ]
